"use client";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { Suspense, useState } from "react";
import { Icon } from "@/components/Icon";
import { DirectionGlyph, ErrorNote, Page, Quote, Row, Section, Segmented, Skeleton, StudyTag, Tag } from "@/components/ui";
import { API, download, PaperDetail, STUDY_TYPE_LABEL } from "@/lib/api";
import { useBookmarks } from "@/lib/bookmarks";
import { TYPE_META } from "@/lib/entities";
import { useApi } from "@/lib/useApi";

export default function PaperPage() {
  return <Suspense><Paper /></Suspense>;
}

function Paper() {
  const { id } = useParams<{ id: string }>();
  const hl = useSearchParams().get("hl");
  const { has, toggle } = useBookmarks();
  const { data: p, error } = useApi<PaperDetail>(`/papers/${id}`);
  const [level, setLevel] = useState<"l1" | "l2" | "l3">("l1");
  const [showAbs, setShowAbs] = useState(false);

  if (error) return <Page title="Publication" back={{ label: "Back" }}><ErrorNote error={error} /></Page>;
  if (!p) return (
    <Page title="Publication" back={{ label: "Back" }}>
      <div className="space-y-3"><Skeleton h={28} w="90%" /><Skeleton h={14} w="60%" /><Skeleton h={120} className="mt-6" /></div>
    </Page>
  );

  const ents = Object.entries(p.labels);
  const byType = (t: string) => ents.filter(([k]) => k.startsWith(t + ":"));

  return (
    <Page title="Publication" back={{ label: "Back" }}
      trailing={
        <>
          <button onClick={() => toggle(p.id)} aria-label={has(p.id) ? "Remove from saved" : "Save paper"} title={has(p.id) ? "Saved" : "Save"}
            className={`btn-press ${has(p.id) ? "text-tint" : ""}`}><Icon name={has(p.id) ? "checkCircle" : "circle"} size={20} /></button>
          <button onClick={() => navigator.share ? navigator.share({ title: p.title, url: location.href }).catch(() => {}) : navigator.clipboard.writeText(location.href)} aria-label="Share" className="btn-press"><Icon name="share" size={20} /></button>
          <a href={p.url} target="_blank" rel="noreferrer" aria-label="Open in PMC" className="btn-press"><Icon name="arrowUpRight" size={20} /></a>
        </>
      }>
      <h2 className="t-title2 mb-2">{p.title}</h2>
      <div className="t-sub text-label-2 mb-3">
        {p.authors.slice(0, 6).join(", ")}{p.authors.length > 6 ? ` +${p.authors.length - 6}` : ""}
        <br />{p.journal ? `${p.journal} · ` : ""}{p.year}{p.doi ? <> · <a className="text-tint" href={`https://doi.org/${p.doi}`} target="_blank" rel="noreferrer">doi</a></> : null}
      </div>
      <div className="flex flex-wrap gap-1.5 mb-6">
        <StudyTag type={p.study_type} />
        {p.duration && <Tag tone="gray">{p.duration.value} {p.duration.unit}</Tag>}
        {p.full_text ? <Tag tone="green">Full text · {(p.word_count ?? 0).toLocaleString()} words</Tag> : <Tag tone="orange">Abstract only</Tag>}
        {p.osdr.length > 0 && <Tag tone="teal">OSDR data</Tag>}
        {p.sample_size ? <Tag>n = {p.sample_size}</Tag> : null}
        {p.dose && <Tag tone="red">{p.dose}</Tag>}
        {p.missions?.map((m) => <Tag key={m} tone="purple">{m}</Tag>)}
      </div>
      {p.duplicate_of && (
        <p className="t-foot text-orange mb-4">
          Likely duplicate of <Link className="underline" href={`/papers/${p.duplicate_of}`}>{p.duplicate_of}</Link>; counted once in evidence totals.
        </p>
      )}

      {hl && <Highlight pid={p.id} chunk={hl} />}

      {/* Summary levels */}
      <div className="bg-bg-2 rounded-2xl p-4 mb-8">
        <div className="flex items-center justify-between gap-3 mb-3">
          <div className="t-headline flex items-center gap-2"><span className="text-indigo"><Icon name="sparkles" size={18} /></span>Summary</div>
          <Segmented size="sm" className="w-[220px]" value={level} onChange={setLevel}
            options={[{ value: "l1", label: "One line" }, { value: "l2", label: "Key points" }, { value: "l3", label: "Detailed" }]} />
        </div>
        {level === "l1" && <p className="t-body">{p.summary.l1}</p>}
        {level === "l2" && <ul className="list-disc pl-5 space-y-1.5 t-body">{p.summary.l2.map((s, i) => <li key={i}>{s}</li>)}</ul>}
        {level === "l3" && <p className="t-body whitespace-pre-line">{p.summary.l3}</p>}
        <div className="t-cap text-label-2 mt-3">{p.summary.method === "llm" ? "Generated by Claude from the full text" : "Extractive — sentences taken verbatim from the paper"}</div>
      </div>

      {/* Entities */}
      <div className="grid sm:grid-cols-2 gap-x-6">
        {["organism", "stressor", "tissue", "platform"].map((t) => byType(t).length > 0 && (
          <Section key={t} header={TYPE_META[t].label}>
            <div className="row flex-wrap gap-1.5">
              {byType(t).map(([k, v]) => (
                <Link key={k} href={`/graph?focus=${encodeURIComponent(k)}`} className="inline-flex items-center gap-1.5 h-[28px] px-2.5 rounded-full bg-fill t-foot font-medium btn-press">
                  <span className="w-2 h-2 rounded-full" style={{ background: TYPE_META[t].color }} />{v}
                </Link>
              ))}
            </div>
          </Section>
        ))}
      </div>

      {/* Findings */}
      <Section header={`Extracted findings (${p.findings.length})`}
        footer="Each finding is backed by a sentence found verbatim in the paper. Direction is relative to controls.">
        {p.findings.length === 0 && <div className="row t-sub text-label-2">No structured findings were extracted from this paper.</div>}
        {p.findings.map((f) => (
          <div key={f.id} className="row block">
            <div className="flex flex-wrap items-center gap-2 mb-2">
              <DirectionGlyph d={f.direction} />
              <span className="t-sub font-medium">{f.labels.outcome}{f.labels.tissue ? ` · ${f.labels.tissue}` : ""}</span>
              <span className="t-cap text-label-2">{[f.labels.stressor, f.labels.organism].filter(Boolean).join(" · ")}</span>
              {f.countermeasure && <Tag tone={f.countermeasure_effect === "effective" ? "green" : "orange"}>{f.labels.countermeasure} · {f.countermeasure_effect}</Tag>}
            </div>
            <Quote section={f.section}>{f.evidence_quote}</Quote>
          </div>
        ))}
      </Section>

      {(p.limitations?.length ?? 0) > 0 && (
        <Section header="Limitations stated by the authors" footer="Sentences taken verbatim from the paper.">
          {p.limitations!.map((l, i) => <div key={i} className="row block"><Quote>{l}</Quote></div>)}
        </Section>
      )}

      {/* Abstract */}
      <Section header="Abstract">
        <div className="row block">
          <p className={`t-body ${showAbs ? "" : "line-clamp-5"}`}>{p.abstract || "No abstract available."}</p>
          {p.abstract && p.abstract.length > 400 && <button onClick={() => setShowAbs(!showAbs)} className="t-sub text-tint mt-1">{showAbs ? "Show less" : "Show more"}</button>}
        </div>
      </Section>

      <div className="grid sm:grid-cols-2 gap-x-6">
        <Section header="Data & source">
          <Row href={p.url} external icon="doc" iconBg="var(--blue)" title="Read on PubMed Central" subtitle={p.id} />
          <Cite id={p.id} />
          {p.osdr.map((o) => <Row key={o.id} href={o.url} external icon="database" iconBg="var(--teal)" title={`OSDR ${o.id}`} subtitle="Open Science Data Repository" />)}
          {Object.keys(p.sections).length > 0 && (
            <Row icon="books" iconBg="var(--gray)" title="Indexed sections" subtitle={Object.entries(p.sections).map(([k, v]) => `${k} ${v}`).join(" · ")} />
          )}
        </Section>
        {p.keywords.length > 0 && (
          <Section header="Keywords">
            <div className="row flex-wrap gap-1.5">{p.keywords.map((k) => <Tag key={k}>{k}</Tag>)}</div>
          </Section>
        )}
      </div>

      {p.related.length > 0 && (
        <Section header="Related publications">
          {p.related.map((r) => <Row key={r.id} href={`/papers/${r.id}`} title={<span className="line-clamp-2 t-sub font-medium">{r.title}</span>} subtitle={`${r.year} · ${STUDY_TYPE_LABEL[r.study_type] ?? r.study_type}`} />)}
        </Section>
      )}
    </Page>
  );
}

function Cite({ id }: { id: string }) {
  const [done, setDone] = useState("");
  const get = (format: "bibtex" | "ris") => fetch(`${API}/api/papers/${id}/cite?format=${format}`).then((r) => r.text());
  const copy = async () => { try { await navigator.clipboard.writeText(await get("bibtex")); setDone("Copied"); setTimeout(() => setDone(""), 1500); } catch {} };
  return (
    <div className="row indent" style={{ "--indent": "57px" } as React.CSSProperties}>
      <span className="grid place-items-center w-[29px] h-[29px] rounded-[7px] text-white shrink-0" style={{ background: "var(--indigo)" }}><Icon name="quote" size={18} stroke={2} /></span>
      <div className="flex-1 t-body">Cite</div>
      <div className="flex gap-3 t-sub">
        <button className="text-tint" onClick={copy}>{done || "Copy BibTeX"}</button>
        <button className="text-tint" onClick={async () => download(`${id}.bib`, await get("bibtex"))}>.bib</button>
        <button className="text-tint" onClick={async () => download(`${id}.ris`, await get("ris"))}>.ris</button>
      </div>
    </div>
  );
}

function Highlight({ pid, chunk }: { pid: string; chunk: string }) {
  const { data } = useApi<{ id: string; section: string; text: string }[]>(`/papers/${pid}/chunks`);
  const c = data?.find((x) => x.id === chunk);
  if (!c) return null;
  return (
    <div className="bg-yellow/10 ring-1 ring-yellow/40 rounded-2xl p-4 mb-6">
      <div className="t-foot font-semibold text-label-2 mb-2">Passage cited in your answer</div>
      <Quote section={c.section}>{c.text}</Quote>
    </div>
  );
}
